### ISSUE TITLE
ros2 param set genicam_driver fails with symbol lookup error on ros2-iron

### ISSUE THREAD

**Issue by DanBmh** [roboception/rc_genicam_driver_ros2#6] opened 2023-06-15 14:02 UTC
Using the apt installation of `ros-iron-rc-genicam-driver` raised following error on setting a parameter:

```
subprocess.CalledProcessError: Command '['bash', '-c', 'ros2 param set /cam_klein_bunt/genicam_driver camera_exp_control "Auto"']' returned non-zero exit status 1.
cam_klein_bunt_1          | /opt/ros/iron/lib/rc_genicam_driver/rc_genicam_driver: symbol lookup error: /opt/ros/iron/lib/librc_genicam_driver_core.so: undefined symbol: _ZN15image_transport16create_publisherEPN6rclcpp4NodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE17rmw_qos_profile_sNS0_29PublisherOptionsWithAllocatorISaIvEEE
cam_klein_bunt_1          | [ros2run]: Process exited with failure 127
```

I could solve it by installing the repository from source.

**Comment by flixr** [comment] 2023-06-15 14:44
closing as duplicate of #5

**Closed as completed by flixr** 2023-06-15 14:44 UTC
